# Generated by Django 5.1.1 on 2024-11-12 16:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('c_megacamion', 'Megacamion'), ('c_articulado', 'Articulado'), ('c_cisterna', 'Cisterna'), ('c_frigorifico', 'Frigorifico'), ('c_lona', 'Lona')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('vehiculo_permitido', models.ManyToManyField(to='app.tipovehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipovehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('correo', models.DateTimeField(default=django.utils.timezone.now)),
                ('aprobado', models.BooleanField(default=False)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculos', models.ManyToManyField(to='app.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('trayecto', models.CharField(max_length=255)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=100, null=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.conductor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehiculo')),
            ],
            options={
                'unique_together': {('vehiculo', 'fecha_inicio', 'fecha_fin')},
            },
        ),
    ]
